### ISSUE TITLE
Panic when pasting large text twice

### ISSUE THREAD

**Issue by scholtzan** [xi-editor/xi-editor#1112]
If I copy `core-lib/view.rs` and paste it twice then xi panics:

```
thread '<xi-syntect-plugin> core host thread' panicked at 'assertion failed: self.start >= amount', rope/src/interval.rs:135:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: xi_rope::interval::Interval::translate_neg
   7: xi_core_lib::linewrap::Lines::patchup_tasks
   8: xi_core_lib::linewrap::Lines::after_edit
   9: xi_core_lib::view::View::after_edit
  10: xi_core_lib::event_context::EventContext::update_views::{{closure}}
  11: core::iter::iterator::Iterator::for_each::{{closure}}
  12: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  13: core::iter::iterator::Iterator::fold::{{closure}}
  14: core::iter::iterator::Iterator::try_fold
  15: core::iter::iterator::Iterator::fold
  16: <core::iter::Chain<A, B> as core::iter::iterator::Iterator>::fold
  17: core::iter::iterator::Iterator::for_each
  18: xi_core_lib::event_context::EventContext::update_views
  19: xi_core_lib::event_context::EventContext::after_edit
  20: xi_core_lib::event_context::EventContext::do_plugin_cmd
  21: xi_core_lib::tabs::CoreState::plugin_notification
  22: <xi_core_lib::core::WeakXiCore as xi_rpc::Handler>::handle_notification
  23: <xi_rpc::RpcLoop<W>>::mainloop::{{closure}}
  24: crossbeam_utils::thread::scope::{{closure}}
  25: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  26: std::panicking::try::do_call
  27: __rust_maybe_catch_panic
  28: std::panicking::try
  29: std::panic::catch_unwind
  30: crossbeam_utils::thread::scope
  31: <xi_rpc::RpcLoop<W>>::mainloop
  32: xi_core_lib::plugins::start_plugin_process::{{closure}}
[2019-02-08][16:43:35][xi_rpc][ERROR] panic guard hit, closing runloop
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: <core::result::Result<T, E>>::unwrap
  10: xi_core_lib::core::XiCore::inner
  11: <xi_core_lib::core::XiCore as xi_rpc::Handler>::handle_notification
  12: <xi_rpc::RpcLoop<W>>::mainloop::{{closure}}
  13: crossbeam_utils::thread::scope::{{closure}}
  14: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  15: std::panicking::try::do_call
  16: __rust_maybe_catch_panic
  17: std::panicking::try
  18: std::panic::catch_unwind
  19: crossbeam_utils::thread::scope
  20: <xi_rpc::RpcLoop<W>>::mainloop
  21: xi_core::main
  22: std::rt::lang_start::{{closure}}
  23: std::panicking::try::do_call
  24: __rust_maybe_catch_panic
  25: std::rt::lang_start_internal
  26: std::rt::lang_start
  27: main
```

Not entirely sure what the problem is.

**Comment by cmyr** [comment]
Interesting, haven't seen this before. The crash is in code I wrote in december, so I'll take a look.

**Comment by ritiek** [comment]
I am able to reproduce this on master only when syntect-plugin is enabled.

**Comment by sjoshid** [comment]
Im experiencing something similar. But it doesnt happen on copy-paste of large text. I have a file with ~110k lines. The file opens up with a lot, A LOT, of
```
stylemap can't resolve 8
```
errors and when I try to clear the file by doing ⌘ A and backspace I get similar stacktrace along with 
```
waiting for lines: (21, 22)
semaphore timeout 31031us timedOut
```
Hope this is helpful in some way.

**Comment by cmyr** [comment]
this should be fixed in https://github.com/xi-editor/xi-editor/pull/1129, if either of you want to try that?

**Comment by sjoshid** [comment]
I hate to be the one to say this but I still get errors
```
stylemap can't resolve 8 <-- thousands of line 
thread 'main' panicked at 'index 1845405 out of range for slice of length 1048576', libcore/slice/mod.rs:2334:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::slice::slice_index_len_fail
   9: <core::ops::range::Range<usize> as core::slice::SliceIndex<[T]>>::index
  10: core::slice::<impl core::ops::index::Index<I> for [T]>::index
  11: xi_plugin_lib::base_cache::ChunkCache::simple_delete
  12: xi_plugin_lib::base_cache::ChunkCache::should_clear
  13: <xi_plugin_lib::base_cache::ChunkCache as xi_plugin_lib::Cache>::update
  14: <xi_plugin_lib::state_cache::StateCache<S> as xi_plugin_lib::Cache>::update
  15: <xi_plugin_lib::view::View<C>>::update
  16: <xi_plugin_lib::dispatch::Dispatcher<'a, P>>::do_update
  17: <xi_plugin_lib::dispatch::Dispatcher<'a, P> as xi_rpc::Handler>::handle_request
  18: <xi_rpc::RpcLoop<W>>::mainloop::{{closure}}
  19: crossbeam_utils::thread::scope::{{closure}}
  20: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  21: std::panicking::try::do_call
  22: __rust_maybe_catch_panic
  23: std::panicking::try
  24: std::panic::catch_unwind
  25: crossbeam_utils::thread::scope
  26: <xi_rpc::RpcLoop<W>>::mainloop
  27: xi_plugin_lib::mainloop
  28: xi_syntect_plugin::main
  29: std::rt::lang_start::{{closure}}
  30: std::panicking::try::do_call
  31: __rust_maybe_catch_panic
  32: std::rt::lang_start_internal
  33: std::rt::lang_start
  34: main
[2019-03-13][20:52:05][xi_core_lib::event_context][ERROR] plugin shutdown, do something PeerDisconnect
[2019-03-13][20:52:05][xi_core_lib::tabs][WARN] plugin PluginPid(1) exited with result Ok(())
client: plugin stopped xi-syntect-plugin
[2019-03-13][20:52:05][xi_core_lib::tabs][DEBUG] Event in open file NoticeRemove("/Users/sujitjoshi/notify/append")
```
But the good news is the UI doesn't crash anymore. I can keep using it like nothing happened. 
Maybe we can ignore the error for now?

**Comment by scholtzan** [comment]
This looks like a issue with xi-syntect. It's probably worth opening a new issue for this.

**Comment by cmyr** [comment]
@sjoshid I agree, this is a different crash. Can you open a new issue with reproduction steps?

**Comment by sjoshid** [comment]
Sure. Created https://github.com/xi-editor/xi-editor/issues/1136.
